### ISSUE TITLE
Formatting time entries is inserting spaces

### ISSUE THREAD

**Issue by martindufort** [lkellar/nova-jsonformatter#3]
Original JSON is: 

```
{'created': '2020-12-24T19:39:56.000Z'}
```

Formatted JSON becomes:
```
{
    'created': '2020-12-24T19: 39: 56.000Z'
}
```
with spaces inserted after the colons in the date. 

This makes it unparseable.

**Comment by lkellar** [comment]
Found the issue, apparently since _technically_ single quotes aren't legal quotes in the JSON spec, the quotes in your example weren't being handled properly. Attempting to format with the same string but with double quotes seemed to work alright.

Anyways, I went ahead and added support for single quotes so your original example should work now:

```
{
    'created': '2020-12-24T19:39:56.000Z'
}
```

**Comment by martindufort** [comment]
All good now. Thanks for making that change.

**Comment by lkellar** [comment]
Just to note, adding support for single quotes broke some instances of valid JSON, so I've removed that feature. As with the JSON spec, only double quotes are supported now
