### ISSUE TITLE
Adds Errors

### ISSUE THREAD

**Issue by ghost** [lkellar/nova-jsonformatter#4]
When I use this, it breaks the JSON and messes up strings. Spaces get deleted, returns added etc. The JSON doesn't pass validation after using the extension and has also crashed Nova.

**Comment by lkellar** [comment]
Sorry about that 😬.

Do you have a sample that reproduces the error so I could investigate the issue?

**Comment by ghost** [comment]
Sure! Here's one simple example that produces a validation error after formatting:
`{
    "display_name": "Prince George's,
    DCArea",
"segment_id": ""
}`

**Comment by lkellar** [comment]
Ah, got it. I'd added support for single quotes in the past, and since single quotes aren't technically valid JSON, the formatter broke on some valid JSON like this where single quotes were part of a string.

I've reversed this feature, so it should work properly now. If it still doesn't work after installing the update (2020.8), let me know

**Comment by ghost** [comment]
Got it, thank you for taking a look at this so quickly!!
